name: Python CI

on:
  push:
    branches: [lab3]

Jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  - name: Install dependencies
    run: |
      python -m venv env
      source env/bin/activate
      pip install -r requirement.txt

  - name: Lint code
    run: |
    source env/bin/activate
    flake8 .
  
  -name: Run test
  run: |
    source env/bin/acivate
    python -m unittest discover -s tests

  