name: Python CI

on:
  push:
    branches: [lab3]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Lint code
      run: |
        source env/bin/activate
        flake8 .

    - name: Run tests
      run: |
        source env/bin/activate
        python -m unittest discover -s tests
  